name: f_charts
description: Another one Flutter Charts library

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  collection: ^1.14.12
  quiver_hashcode: ^2.0.0
  shared:
    path: ../shared
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
