name: pubspec_semver
description: A sample command-line application.

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  plain_optional: ^0.1.3
  pubspec_yaml: ^2.0.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
